name: gammer
description: GAMMER app with videos, tournaments, and livestream.

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.17.4
  firebase_storage: ^11.6.6
  permission_handler: ^11.3.0
  agora_rtc_engine: ^6.2.3
  file_picker: ^8.0.0
  video_player: ^2.8.2
  image_picker: ^1.0.4
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/avatar.png
