name: gammer_fixed
description: GAMMER app with videos, tournaments, and livestream.

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.6.6
  firebase_messaging: ^14.7.10   # ✅ Compatible with firebase_core ^2.x
  permission_handler: ^11.3.0
  agora_rtc_engine: ^6.2.3
  file_picker: ^8.0.0
  video_player: ^2.8.2
  image_picker: ^1.0.4
  uuid: ^4.3.3

  # Local flutter_local_notifications
  flutter_local_notifications:
    path: local_plugins/flutter_local_notifications-14.0.1

  flutter_plugin_android_lifecycle: ^2.0.15
  share_plus: ^10.0.0

  # ✅ Supabase dependencies
  supabase_flutter: ^2.6.0
  postgrest: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/avatar.png
