// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaiyP19xTV3CdtGhrAbKsRq6atOVmCD_M',
    appId: '1:318544045968:web:3bab38ee945f51f4793515',
    messagingSenderId: '318544045968',
    projectId: 'gammer-test',
    authDomain: 'gammer-test.firebaseapp.com',
    storageBucket: 'gammer-test.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkBRNSkv2uROKkXtW5B5BzjaHFnrrHZ4k',
    appId: '1:318544045968:android:68203296026ac2a2793515',
    messagingSenderId: '318544045968',
    projectId: 'gammer-test',
    storageBucket: 'gammer-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ-nWgSiTZrwX3jHHLjpJYakJAHLI2AsY',
    appId: '1:318544045968:ios:3079bc8856575f1b793515',
    messagingSenderId: '318544045968',
    projectId: 'gammer-test',
    storageBucket: 'gammer-test.firebasestorage.app',
    iosBundleId: 'com.example.gammerFixed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ-nWgSiTZrwX3jHHLjpJYakJAHLI2AsY',
    appId: '1:318544045968:ios:3079bc8856575f1b793515',
    messagingSenderId: '318544045968',
    projectId: 'gammer-test',
    storageBucket: 'gammer-test.firebasestorage.app',
    iosBundleId: 'com.example.gammerFixed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaiyP19xTV3CdtGhrAbKsRq6atOVmCD_M',
    appId: '1:318544045968:web:d214eb3a9c977fa8793515',
    messagingSenderId: '318544045968',
    projectId: 'gammer-test',
    authDomain: 'gammer-test.firebaseapp.com',
    storageBucket: 'gammer-test.firebasestorage.app',
  );

}