// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm89FZ-skQZSW1-uy0DBtxF3BZqHBL4sg',
    appId: '1:563746270812:web:13a93c32ff655d51640099',
    messagingSenderId: '563746270812',
    projectId: 'gammer-fixed',
    authDomain: 'gammer-fixed.firebaseapp.com',
    storageBucket: 'gammer-fixed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5bk_DqHgc4yN1wT4iWZUZrvpmMCcMwpw',
    appId: '1:563746270812:android:5f6c59f95ed573fb640099',
    messagingSenderId: '563746270812',
    projectId: 'gammer-fixed',
    storageBucket: 'gammer-fixed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPvhwBzvSe5bY1ZUCTN7nDvcxwI0-l468',
    appId: '1:563746270812:ios:61c015a214773623640099',
    messagingSenderId: '563746270812',
    projectId: 'gammer-fixed',
    storageBucket: 'gammer-fixed.firebasestorage.app',
    iosBundleId: 'com.example.gammerFixed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPvhwBzvSe5bY1ZUCTN7nDvcxwI0-l468',
    appId: '1:563746270812:ios:61c015a214773623640099',
    messagingSenderId: '563746270812',
    projectId: 'gammer-fixed',
    storageBucket: 'gammer-fixed.firebasestorage.app',
    iosBundleId: 'com.example.gammerFixed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm89FZ-skQZSW1-uy0DBtxF3BZqHBL4sg',
    appId: '1:563746270812:web:91ea1882c1b551b5640099',
    messagingSenderId: '563746270812',
    projectId: 'gammer-fixed',
    authDomain: 'gammer-fixed.firebaseapp.com',
    storageBucket: 'gammer-fixed.firebasestorage.app',
  );
}
